import { Currency } from '@/types/currency';

export const CURRENCIES: Currency[] = [
  { code: 'USD', name: 'US Dollar', symbol: '$', locale: 'en-US' },
  { code: 'EUR', name: 'Euro', symbol: '€', locale: 'de-DE' },
  { code: 'GBP', name: 'British Pound', symbol: '£', locale: 'en-GB' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', locale: 'ja-JP' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'CA$', locale: 'en-CA' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', locale: 'en-AU' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', locale: 'de-CH' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', locale: 'zh-CN' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', locale: 'en-IN' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', locale: 'pt-BR' },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'MX$', locale: 'es-MX' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', locale: 'ko-KR' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', locale: 'en-SG' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', locale: 'zh-HK' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', locale: 'sv-SE' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', locale: 'nb-NO' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', locale: 'da-DK' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', locale: 'en-NZ' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', locale: 'en-ZA' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', locale: 'th-TH' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', locale: 'ms-MY' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', locale: 'id-ID' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', locale: 'en-PH' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', locale: 'vi-VN' },
  { code: 'TWD', name: 'Taiwan Dollar', symbol: 'NT$', locale: 'zh-TW' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', locale: 'ar-AE' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', locale: 'ar-SA' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'QR', locale: 'ar-QA' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD', locale: 'ar-KW' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BD', locale: 'ar-BH' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'OMR', locale: 'ar-OM' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD', locale: 'ar-JO' },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', locale: 'he-IL' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', locale: 'tr-TR' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', locale: 'ru-RU' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', locale: 'pl-PL' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', locale: 'cs-CZ' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', locale: 'hu-HU' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', locale: 'ro-RO' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', locale: 'bg-BG' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', locale: 'hr-HR' },
  { code: 'ISK', name: 'Icelandic Krona', symbol: 'kr', locale: 'is-IS' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', locale: 'uk-UA' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', locale: 'ka-GE' },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', locale: 'hy-AM' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', locale: 'az-AZ' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', locale: 'kk-KZ' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'soʻm', locale: 'uz-UZ' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', locale: 'ur-PK' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', locale: 'bn-BD' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', locale: 'si-LK' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'Rs', locale: 'ne-NP' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', locale: 'my-MM' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', locale: 'km-KH' },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭', locale: 'lo-LA' },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', locale: 'ms-BN' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', locale: 'en-FJ' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', locale: 'en-MU' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', locale: 'dv-MV' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', locale: 'ps-AF' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', locale: 'fa-IR' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', locale: 'ar-IQ' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', locale: 'ar-LB' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', locale: 'ar-EG' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'LD', locale: 'ar-LY' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'DT', locale: 'ar-TN' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'DA', locale: 'ar-DZ' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD', locale: 'ar-MA' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', locale: 'en-GH' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', locale: 'en-NG' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', locale: 'en-KE' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', locale: 'sw-TZ' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', locale: 'en-UG' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'RF', locale: 'rw-RW' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', locale: 'am-ET' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', locale: 'pt-AO' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', locale: 'pt-MZ' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', locale: 'en-ZM' },
  { code: 'BWP', name: 'Botswana Pula', symbol: 'P', locale: 'en-BW' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$', locale: 'en-NA' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', locale: 'mg-MG' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', locale: 'fr-CD' },
  { code: 'XAF', name: 'Central African CFA', symbol: 'FCFA', locale: 'fr-CM' },
  { code: 'XOF', name: 'West African CFA', symbol: 'CFA', locale: 'fr-SN' },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', locale: 'fr-PF' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', locale: 'es-PE' },
  { code: 'CLP', name: 'Chilean Peso', symbol: 'CL$', locale: 'es-CL' },
  { code: 'COP', name: 'Colombian Peso', symbol: 'CO$', locale: 'es-CO' },
  { code: 'ARS', name: 'Argentine Peso', symbol: 'AR$', locale: 'es-AR' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', locale: 'es-UY' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', locale: 'es-PY' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', locale: 'es-BO' },
  { code: 'VES', name: 'Venezuelan Bolivar', symbol: 'Bs.S', locale: 'es-VE' },
  { code: 'TTD', name: 'Trinidad Dollar', symbol: 'TT$', locale: 'en-TT' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', locale: 'en-JM' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: 'Bds$', locale: 'en-BB' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: 'B$', locale: 'en-BS' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', locale: 'es-DO' },
  { code: 'CRC', name: 'Costa Rican Colon', symbol: '₡', locale: 'es-CR' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', locale: 'es-GT' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', locale: 'es-HN' },
  { code: 'NIO', name: 'Nicaraguan Cordoba', symbol: 'C$', locale: 'es-NI' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/', locale: 'es-PA' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'Afl', locale: 'nl-AW' },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: 'CI$', locale: 'en-KY' },
  { code: 'BMD', name: 'Bermudian Dollar', symbol: 'BD$', locale: 'en-BM' },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', locale: 'en-BZ' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', locale: 'en-AG' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', locale: 'fr-HT' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '₱', locale: 'es-CU' },
  { code: 'GYD', name: 'Guyanese Dollar', symbol: 'GY$', locale: 'en-GY' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: 'SR$', locale: 'nl-SR' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', locale: 'mn-MN' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', locale: 'tg-TJ' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'сом', locale: 'ky-KG' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', locale: 'tk-TM' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: 'SRe', locale: 'en-SC' },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E', locale: 'en-SZ' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'M', locale: 'en-LS' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', locale: 'en-MW' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh', locale: 'so-SO' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'SDG', locale: 'ar-SD' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', locale: 'ti-ER' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', locale: 'fr-DJ' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', locale: 'en-GM' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', locale: 'fr-GN' },
  { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le', locale: 'en-SL' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'L$', locale: 'en-LR' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: 'Esc', locale: 'pt-CV' },
  { code: 'STN', name: 'Sao Tome Dobra', symbol: 'Db', locale: 'pt-ST' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', locale: 'fr-BI' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', locale: 'fr-KM' },
  { code: 'TOP', name: 'Tongan Paanga', symbol: 'T$', locale: 'to-TO' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', locale: 'sm-WS' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', locale: 'bi-VU' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', locale: 'en-SB' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', locale: 'en-PG' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu', locale: 'dz-BT' },
  { code: 'SYP', name: 'Syrian Pound', symbol: 'S£', locale: 'ar-SY' },
  { code: 'YER', name: 'Yemeni Rial', symbol: 'YR', locale: 'ar-YE' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'din', locale: 'sr-RS' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', locale: 'mk-MK' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', locale: 'sq-AL' },
  { code: 'BAM', name: 'Bosnia Mark', symbol: 'KM', locale: 'bs-BA' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', locale: 'ro-MD' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', locale: 'be-BY' },
];

export function getCurrency(code: string): Currency | undefined {
  return CURRENCIES.find((c) => c.code === code);
}

export function formatCurrency(amount: number, currencyCode: string): string {
  try {
    const currency = getCurrency(currencyCode);
    return new Intl.NumberFormat(currency?.locale || 'en-US', {
      style: 'currency',
      currency: currencyCode,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(amount);
  } catch {
    return `${currencyCode} ${amount.toFixed(2)}`;
  }
}
